//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using EduRp.Data.Core.Foundation;
    using System;
    using System.Collections.Generic;
    
    public partial class AcadLessonPlan:BaseEntity
    {
        public int AcadLessonPlanId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public string Meeting { get; set; }
        public string StandardofCompetance { get; set; }
        public string BasicCompetance { get; set; }
        public string Indicator { get; set; }
        public Nullable<int> TimeAllocation { get; set; }
        public string InstructiveObjective { get; set; }
        public string TeachingMaterial { get; set; }
        public string TeachingMethod { get; set; }
        public string CharacterImplementation { get; set; }
        public string IntialActivity { get; set; }
        public string MainActivity { get; set; }
        public string ClosingActivity { get; set; }
        public Nullable<int> LearningScore { get; set; }
        public string Assessment { get; set; }
        public string SubjectTeacher { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
