//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using EduRp.Data.Core.Foundation;
    using System;
    using System.Collections.Generic;
    
    public partial class AcadStudentLeaveApplication:BaseEntity
    {
        public int AcadStudentLeaveApplicationId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<System.DateTime> StudentLeaveApplicationDate { get; set; }
        public Nullable<int> Section { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string StudentName { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> StudentStartDate { get; set; }
        public Nullable<System.DateTime> StudentEndDate { get; set; }
        public string HomeRoomName { get; set; }
        public string Attachement { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
