//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using EduRp.Data.Core.Foundation;
    using System;
    using System.Collections.Generic;
    
    public partial class AcadHcareNurseNote:BaseEntity
    {
        public int AcadHcareNurseNoteId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public int StudentId { get; set; }
        public Nullable<System.DateTime> SickDate { get; set; }
        public string Description { get; set; }
        public string Prescription { get; set; }
        public string NurseName { get; set; }
        public string Attachement { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
