//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcadExamResultAssesRpt
    {
        public int AcadExamResultAssesRptId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string ReportName { get; set; }
        public string Result { get; set; }
        public string Remarks { get; set; }
        public string ReportedBy { get; set; }
        public string HomeRoom { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
